const mongoose = require("mongoose");


const poolsRegister = new mongoose.Schema({
        F0U1:{
        pool0:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        pool1:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        pool2:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        hashRate:Number,
        expectedHash:Number,
        difHash:Number,
        difHashPorcent:Number,
        hashRateAvg15m:Number, hashRateAvg1h:Number,hashRateAvg24h:Number
        },
        F0U2:{
        pool0:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        pool1:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        pool2:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        hashRate:Number,
        expectedHash:Number,
        difHash:Number,
        difHashPorcent:Number,
        hashRateAvg15m:Number, hashRateAvg1h:Number,hashRateAvg24h:Number
        },     
       F1U1:{
        pool0:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        pool1:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        pool2:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        hashRate:Number,
        expectedHash:Number,
        difHash:Number,
        difHashPorcent:Number,
        hashRateAvg15m:Number, hashRateAvg1h:Number,hashRateAvg24h:Number
        },
       F1U2:{
        pool0:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        pool1:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        pool2:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        hashRate:Number,
        expectedHash:Number,
        difHash:Number,
        difHashPorcent:Number,
        hashRateAvg15m:Number, hashRateAvg1h:Number,hashRateAvg24h:Number
        },
       F1U3:{
        pool0:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        pool1:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        pool2:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        hashRate:Number,
        expectedHash:Number,
        difHash:Number,
        difHashPorcent:Number,
        hashRateAvg15m:Number, hashRateAvg1h:Number,hashRateAvg24h:Number
        },
       F1U4:{
       pool0:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        pool1:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        pool2:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        hashRate:Number,
        expectedHash:Number,
        difHash:Number,
        difHashPorcent:Number,
        hashRateAvg15m:Number, hashRateAvg1h:Number,hashRateAvg24h:Number
        },
    
       F2U1:{
        pool0:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        pool1:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        pool2:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        hashRate:Number,
        expectedHash:Number,
        difHash:Number,
        difHashPorcent:Number,
        hashRateAvg15m:Number, hashRateAvg1h:Number,hashRateAvg24h:Number
        },
       F2U2:{
        pool0:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        pool1:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        pool2:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        hashRate:Number,
        expectedHash:Number,
        difHash:Number,
        difHashPorcent:Number,
        hashRateAvg15m:Number, hashRateAvg1h:Number,hashRateAvg24h:Number
        },
       F2U3:{
        pool0:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        pool1:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        pool2:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        hashRate:Number,
        expectedHash:Number,
        difHash:Number,
        difHashPorcent:Number,
        hashRateAvg15m:Number, hashRateAvg1h:Number,hashRateAvg24h:Number
        },
       F2U4:{
        pool0:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        pool1:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        pool2:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        hashRate:Number,
        expectedHash:Number,
        difHash:Number,
        difHashPorcent:Number,
        hashRateAvg15m:Number, hashRateAvg1h:Number,hashRateAvg24h:Number
        },
       F2U5:{
        pool0:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        pool1:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        pool2:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        hashRate:Number,
        expectedHash:Number,
        difHash:Number,
        difHashPorcent:Number,
        hashRateAvg15m:Number, hashRateAvg1h:Number,hashRateAvg24h:Number
        },
       F2U6:{
        pool0:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        pool1:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        pool2:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        hashRate:Number,
        expectedHash:Number,
        difHash:Number,
        difHashPorcent:Number,
        hashRateAvg15m:Number, hashRateAvg1h:Number,hashRateAvg24h:Number
        },
       F2U7:{
        pool0:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        pool1:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        pool2:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        hashRate:Number,
        expectedHash:Number,
        difHash:Number,
        difHashPorcent:Number,
        hashRateAvg15m:Number, hashRateAvg1h:Number,hashRateAvg24h:Number
        },
       F2U8:{
        pool0:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        pool1:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        pool2:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        hashRate:Number,
        expectedHash:Number,
        difHash:Number,
        difHashPorcent:Number,
        hashRateAvg15m:Number, hashRateAvg1h:Number,hashRateAvg24h:Number
        },   
    
       F3U1:{
        pool0:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        pool1:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        pool2:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        hashRate:Number,
        expectedHash:Number,
        difHash:Number,
        difHashPorcent:Number,
        hashRateAvg15m:Number, hashRateAvg1h:Number,hashRateAvg24h:Number
        },
       F3U2:{
        pool0:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        pool1:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        pool2:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        hashRate:Number,
        expectedHash:Number,
        difHash:Number,
        difHashPorcent:Number,
        hashRateAvg15m:Number, hashRateAvg1h:Number,hashRateAvg24h:Number
        },
       F3U3:{
        pool0:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        pool1:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        pool2:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        hashRate:Number,
        expectedHash:Number,
        difHash:Number,
        difHashPorcent:Number,
        hashRateAvg15m:Number, hashRateAvg1h:Number,hashRateAvg24h:Number
        },
       F3U4:{
        pool0:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        pool1:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        pool2:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        hashRate:Number,
        expectedHash:Number,
        difHash:Number,
        difHashPorcent:Number,
        hashRateAvg15m:Number, hashRateAvg1h:Number,hashRateAvg24h:Number
        },    
    
       F4U1:{
        pool0:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        pool1:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        pool2:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        hashRate:Number,
        expectedHash:Number,
        difHash:Number,
        difHashPorcent:Number,
        hashRateAvg15m:Number, hashRateAvg1h:Number,hashRateAvg24h:Number
        },
       F4U2:{
        pool0:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        pool1:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        pool2:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        hashRate:Number,
        expectedHash:Number,
        difHash:Number,
        difHashPorcent:Number,
        hashRateAvg15m:Number, hashRateAvg1h:Number,hashRateAvg24h:Number
        },
       F4U3:{
        pool0:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        pool1:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        pool2:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        hashRate:Number,
        expectedHash:Number,
        difHash:Number,
        difHashPorcent:Number,
        hashRateAvg15m:Number, hashRateAvg1h:Number,hashRateAvg24h:Number
        },
       F4U4:{
        pool0:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        pool1:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        pool2:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        hashRate:Number,
        expectedHash:Number,
        difHash:Number,
        difHashPorcent:Number,
        hashRateAvg15m:Number, hashRateAvg1h:Number,hashRateAvg24h:Number
        },
       F4U5:{
        pool0:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        pool1:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        pool2:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        hashRate:Number,
        expectedHash:Number,
        difHash:Number,
        difHashPorcent:Number,
        hashRateAvg15m:Number, hashRateAvg1h:Number,hashRateAvg24h:Number
        },    
    
       F5U1:{
        pool0:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        pool1:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        pool2:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        hashRate:Number,
        expectedHash:Number,
        difHash:Number,
        difHashPorcent:Number,
        hashRateAvg15m:Number, hashRateAvg1h:Number,hashRateAvg24h:Number
        },
       F5U2:{
        pool0:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        pool1:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        pool2:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        hashRate:Number,
        expectedHash:Number,
        difHash:Number,
        difHashPorcent:Number,
        hashRateAvg15m:Number, hashRateAvg1h:Number,hashRateAvg24h:Number
        },
       F5U3:{
        pool0:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        pool1:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        pool2:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        hashRate:Number,
        expectedHash:Number,
        difHash:Number,
        difHashPorcent:Number,
        hashRateAvg15m:Number, hashRateAvg1h:Number,hashRateAvg24h:Number
        },
       F5U4:{
           pool0:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        pool1:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        pool2:{
                Total:Number,
                Active:Number,
                Dead:Number,
                Inactive:Number,
                hashRate:Number
            },
        hashRate:Number,
        expectedHash:Number,
        difHash:Number,
        difHashPorcent:Number,
        hashRateAvg15m:Number, hashRateAvg1h:Number,hashRateAvg24h:Number
        },    
       F0:{
        pool0:{
            hashRate:Number
        },
        pool1:{
            hashRate:Number
        },
        pool2:{
            hashRate:Number
        },
        hashRate:Number,
        expectedHash:Number,
        difHash:Number,
        difHashPorcent:Number,
        hashRateAvg15m:Number, hashRateAvg1h:Number,hashRateAvg24h:Number
        },
       F1:{
        pool0:{
            hashRate:Number
        },
        pool1:{
            hashRate:Number
        },
        pool2:{
            hashRate:Number
        },
        hashRate:Number,
        expectedHash:Number,
        difHash:Number,
        difHashPorcent:Number,
        hashRateAvg15m:Number, hashRateAvg1h:Number,hashRateAvg24h:Number
        },
       F2:{
        pool0:{
            hashRate:Number
        },
        pool1:{
            hashRate:Number
        },
        pool2:{
            hashRate:Number
        },
        hashRate:Number,
        expectedHash:Number,
        difHash:Number,
        difHashPorcent:Number,
        hashRateAvg15m:Number, hashRateAvg1h:Number,hashRateAvg24h:Number
        },
       F3:{
        pool0:{
            hashRate:Number
        },
        pool1:{
            hashRate:Number
        },
        pool2:{
            hashRate:Number
        },
        hashRate:Number,
        expectedHash:Number,
        difHash:Number,
        difHashPorcent:Number,
        hashRateAvg15m:Number, hashRateAvg1h:Number,hashRateAvg24h:Number
        },
       F4:{
        pool0:{
            hashRate:Number
        },
        pool1:{
            hashRate:Number
        },
        pool2:{
            hashRate:Number
        },
        hashRate:Number,
        expectedHash:Number,
        difHash:Number,
        difHashPorcent:Number,
        hashRateAvg15m:Number, hashRateAvg1h:Number,hashRateAvg24h:Number
        },
       F5:{
        pool0:{
            hashRate:Number
        },
        pool1:{
            hashRate:Number
        },
        pool2:{
            hashRate:Number
        },
        hashRate:Number,
        expectedHash:Number,
        difHash:Number,
        difHashPorcent:Number,
        hashRateAvg15m:Number, hashRateAvg1h:Number,hashRateAvg24h:Number
        },
       totalCoin:{
        pool0:{
            hashRate:Number
        },
        pool1:{
            hashRate:Number
        },
        pool2:{
            hashRate:Number
        },
        hashRate:Number,
        expectedHash:Number,
        difHash:Number,
        difHashPorcent:Number,
        hashRateAvg15m:Number, hashRateAvg1h:Number,hashRateAvg24h:Number
        },
        Date: Date
});

const PoolsReg = mongoose.model('PoolsReg', poolsRegister);

module.exports = PoolsReg;